application/models.py
from datetime import datetime

from flask.ext.security import UserMixin, RoleMixin
from sqlalchemy import event
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.ext.orderinglist import ordering_list

from application import db


class Base(db.Model):

    """A base class that automatically creates the table name and
    primary key.
    """

    __abstract__ = True
    id = db.Column(db.Integer, primary_key=True)

    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()


class TimestampMixin(object):
    created = db.Column(db.DateTime, default=datetime.utcnow)
    updated = db.Column(db.DateTime, default=datetime.utcnow)

    def readable_date(self, date, format='%H:%M on %-d %B'):
        """Format the given date using the given format."""
        return date.strftime(format)


# Authentication
# ~~~~~~~~~~~~~~
class UserRoleAssoc(db.Model):

    """Associates a user with a role."""

    __tablename__ = 'user_role_assoc'
    user_id = db.Column(db.ForeignKey('user.id'), primary_key=True)
    role_id = db.Column(db.ForeignKey('role.id'), primary_key=True)


class User(Base, UserMixin):

    """
    A forum user. `UserMixin` provides the following methods:

        `is_active(self)`
            Returns ``True`` if the user is active.

        `is_authenticated(self)`
            Always returns ``True``.

        `is_anonymous(self)`
            Always returns ``False``.

        `get_auth_token(self)`
            Returns the user's authentication token.

        `has_role(self, role)`
            Returns ``True`` if the user identifies with the specified role.

        `get_id(self)`
            Returns ``self.id``.

        `__eq__(self, other)`
            Returns ``True`` if the two users have the same id.

        `__ne__(self, other)`
            Returns the opposite of `__eq__`.
    """

    email = db.Column(db.String, unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean)
    created = db.Column(db.DateTime, default=datetime.utcnow)

    roles = db.relationship('Role', secondary='user_role_assoc',
                            backref='users')

    def __repr__(self):
        return '<User(%s, %s)>' % (self.id, self.email)

    def __unicode__(self):
        return self.email


class Role(Base, RoleMixin):

    """
    A specific role. `RoleMixin` provides the following methods:

        `__eq__(self, other)`
            Returns ``True`` if the `name` attributes are the same. If
            `other` is a string, returns `self.name == other`.

        `__ne__(self, other)`
    """

    name = db.Column(db.String)
    description = db.Column(db.String)

    def __repr__(self):
        return '<Role(%s, %s)>' % (self.id, self.name)


# Forum
# ~~~~~
class Board(Base):

    #: The human-readable name, e.g. "Python 3"
    name = db.Column(db.String)

    #: The URL-encoded name, e.g. "python-3"
    slug = db.Column(db.String, unique=True)

    #: A short description of what the board contains.
    description = db.Column(db.Text)

    #: The threads associated with this board.
    threads = db.relationship('Thread', cascade='all,delete', backref='board')

    def __unicode__(self):
        return self.name


class Thread(Base, TimestampMixin):
    name = db.Column(db.String(80))

    #: The original author of the thread.
    author_id = db.Column(db.ForeignKey('user.id'), index=True)
    author = db.relationship('User', backref='threads')

    #: The parent board.
    board_id = db.Column(db.ForeignKey('board.id'), index=True)

    #: An ordered collection of posts
    posts = db.relationship('Post', backref='thread',
                            cascade='all,delete',
                            order_by='Post.index',
                            collection_class=ordering_list('index'))

    #: Length of the threads
    length = db.Column(db.Integer, default=0)

    def __unicode__(self):
        return self.name


class Post(Base, TimestampMixin):
    #: Used to order the post within its :class:`Thread`
    index = db.Column(db.Integer, default=0, index=True)

    #: The post content. The site views expect Markdown by default, but
    #: you can store anything here.
    content = db.Column(db.Text)

    #: The original author of the post.
    author_id = db.Column(db.ForeignKey('user.id'), index=True)
    author = db.relationship('User', backref='posts')

    #: The parent thread.
    thread_id = db.Column(db.ForeignKey('thread.id'), index=True)


    def __repr__(self):
        return '<Post(%s)>' % self.id


def thread_posts_append(thread, post, initiator):
    """Update some thread values when `Thread.posts.append` is called."""
    thread.length += 1
    thread.updated = datetime.utcnow()

event.listen(Thread.posts, 'append', thread_posts_append)

application/forum/forms.py
from flask.ext.wtf import Form
from wtforms import SubmitField, TextField, TextAreaField
from wtforms.validators import Required


class CreateThreadForm(Form):
    name = TextField(validators=[Required()])
    content = TextAreaField(validators=[Required()])
    submit = SubmitField()


class CreatePostForm(Form):
    content = TextAreaField(validators=[Required()])
    submit = SubmitField()


class EditPostForm(CreatePostForm):
    pass

application/__init__.py
from flask import Flask, render_template
from flask.ext.assets import Bundle, Environment
from flask.ext.markdown import Markdown
from flask.ext.security import Security, SQLAlchemyUserDatastore
from flask.ext.sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config.from_object('config')


# Assets
assets = Environment(app)
assets.url = '/static'
assets.directory = app.config['ASSETS_DEST']

less = Bundle('less/style.less', filters='less', output='gen/style.css')
assets.register('all-css', less)


# Database
db = SQLAlchemy(app)
import models


# Admin
import admin


# Markdown
Markdown(app, safe_mode='escape')


# Debug toolbar
if app.config['DEBUG']:
    from flask.ext.debugtoolbar import DebugToolbarExtension as DTE
    toolbar = DTE(app)


# Security
datastore = SQLAlchemyUserDatastore(db, models.User, models.Role)
security = Security(app, datastore)


# Endpoints
@app.route('/')
def index():
    return render_template('index.html', User=models.User)


import forum.views as forum
app.register_blueprint(forum.bp, url_prefix='/forum')

application/forum/views.py
from sqlalchemy.exc import SQLAlchemyError as sql_exc
from flask import Blueprint, redirect, render_template, url_for
from flask.ext.security import current_user, login_required

from application import db
from application.models import Board, Thread, Post, User
import forms

GET_POST = ['GET', 'POST']

bp = Blueprint('forum', __name__)


@bp.route('/')
def index():
    boards = Board.query.all()
    return render_template('index.html', boards=boards)


@bp.route('/<slug>/')
def board(slug):
    try:
        board = Board.query.filter(Board.slug == slug).one()
        threads = Thread.query.filter(Thread.board_id == board.id) \
                        .order_by(Thread.updated.desc()).all()
    except sql_exc:
        return redirect(url_for('.index'))

    return render_template('forum/board.html', board=board,
                           threads=threads)


@bp.route('/<slug>/<int:id>')
@bp.route('/<slug>/<int:id>-<title>')
def thread(slug, id, title=None):
    try:
        board = Board.query.filter(Board.slug == slug).one()
    except sql_exc:
        return redirect(url_for('.index'))

    try:
        thread = Thread.query.filter(Thread.id == id).one()
    except sql_exc:
        return redirect(url_for('.board', slug=slug))

    return render_template('forum/thread.html', board=board, thread=thread,
                           posts=thread.posts)


@bp.route('/users/<int:id>')
def user(id):
    try:
        user = User.query.filter(User.id == id).one()
    except sql_exc:
        return redirect(url_for('.index'))

    return render_template('forum/user.html', user=user)


@bp.route('/<slug>/create/', methods=GET_POST)
@login_required
def create_thread(slug):
    try:
        board = Board.query.filter(Board.slug == slug).one()
    except sql_exc:
        return redirect(url_for('.index'))

    form = forms.CreateThreadForm()
    if form.validate_on_submit():
        t = Thread( name=form.name.data, board=board, author=current_user)
        db.session.add(t)
        db.session.flush()

        p = Post(content=form.content.data, author=current_user)
        t.posts.append(p)
        db.session.commit()

        return redirect(url_for('.board', slug=slug))

    return render_template('forum/create_thread.html', board=board,
                           form=form)


@bp.route('/<slug>/<int:id>/create', methods=GET_POST)
@login_required
def create_post(slug, id):
    try:
        board = Board.query.filter(Board.slug == slug).one()
    except sql_exc:
        return redirect(url_for('.index'))
    try:
        thread = Thread.query.filter(Thread.id == id).one()
    except sql_exc:
        return redirect(url_for('.board', slug=slug))

    form = forms.CreatePostForm()
    if form.validate_on_submit():
        p = Post(content=form.content.data, author=current_user)
        thread.posts.append(p)
        db.session.flush()
        thread.updated = p.created
        db.session.commit()

        return redirect(url_for('.thread', slug=slug, id=id))

    return render_template('forum/create_post.html', board=board,
                           thread=thread, form=form)


@bp.route('/<slug>/<int:thread_id>/<int:post_id>/edit', methods=GET_POST)
@login_required
def edit_post(slug, thread_id, post_id):
    try:
        board = Board.query.filter(Board.slug == slug).one()
    except sql_exc:
        return redirect(url_for('.index'))
    try:
        thread = Thread.query.filter(Thread.id == thread_id).one()
    except sql_exc:
        return redirect(url_for('.board', slug=slug))

    thread_redirect = redirect(url_for('.thread', slug=slug, id=thread_id))
    try:
        post = Post.query.filter(Post.id == post_id).one()
    except sql_exc:
        return thread_redirect
    if post.author_id != current_user.id:
        return thread_redirect

    form = forms.EditPostForm()
    if form.validate_on_submit():
        post.content = form.content.data
        db.session.commit()
        return thread_redirect
    else:
        form.content.data = post.content

    return render_template('forum/create_post.html', board=board,
                           thread=thread, form=form)

application/templates/forum/board.html
{% extends 'forum/layout.html' %}
{% import 'forum/macros.html' as m %}

{# #}
{% macro thread_row(t) %}
    <tr>
        <td><a href="{{ url_for('.thread', slug=board.slug, id=t.id) }}">{{ t.name }}</a></td>
        <td>{{ t.length }}</td>
        <td>{{ t.readable_date(t.updated) }}</td>
    </tr>
{% endmacro %}

{% block title %}{{ board.name }}{% endblock %}

{% block body %}
{{ m.breadcrumbs(board) }}
<h1>{{ board.name }}</h1>

<a href="{{ url_for('.create_thread', slug=board.slug) }}">New thread</a>
<table id="threads">
    <tr>
        <th>Subject</th>
        <th>Posts</th>
        <th>Last updated</th>
    </tr>
    {% for t in threads %}{{ thread_row(t) }}{% endfor %}
</table>
{% endblock %}

application/templates/forum/create_post.html
{% extends 'forum/layout.html' %}
{% import 'forum/macros.html' as m %}

{% block title %}{% endblock %}

{% block body %}
<h1>{{ thread.name }}</h1>

<form method="POST" action="">
    {{ form.csrf_token }}
    {{ form.content }}
    {{ form.submit }}
</form>
{% endblock %}

application/templates/forum/create_thread.html
{% extends 'forum/layout.html' %}
{% import 'forum/macros.html' as m %}

{% block title %}{% endblock %}

{% block body %}
<h1>{{ board.name }}</h1>

<form method="POST" action="">
    {{ form.csrf_token }}
    {{ form.name }}
    {{ form.content }}
    {{ form.submit }}
</form>
{% endblock %}

application/templates/forum/edit_post.html
{% extends 'forum/layout.html' %}
{% import 'forum/macros.html' as m %}

{% block title %}Edit post in "{{ thread.name }}"{% endblock %}

{% block body %}
<h1>{{ thread.name }}</h1>

<form method="POST" action="">
    {{ form.csrf_token }}
    {{ form.content }}
    {{ form.submit }}
</form>
{% endblock %}

application/templates/forum/index.html
{% extends 'forum/layout.html' %}
{% import 'forum/macros.html' as m %}

{% block title %}Forum{% endblock %}

{% block body %}
{{ m.breadcrumbs(board) }}
<h1>Forum</h1>

{% for b in boards %}
    <h2><a href="{{ url_for('.board', slug=b.slug) }}">{{ b.name }}</a></h2>
    <p>{{ b.description }}</p>
{% endfor %}
{% endblock %}

application/templates/forum/layout.html
{% extends 'layout.html' %}

application/templates/forum/macros.html
{# Breadcrumb navigation #}
{% macro breadcrumbs(board=none, thread=none) %}
<div class="breadcrumbs">
    <a href="{{ url_for('index') }}">Index</a>
    &raquo; <a href="{{ url_for('forum.index') }}">Forum</a>
    {% if board %}
    &raquo; <a href="{{ url_for('forum.board', slug=board.slug) }}">{{ board.name }}</a>
        {% if thread %}
        &raquo; <a href="{{ url_for('forum.thread', slug=board.slug, id=thread.id) }}">{{ thread.name }}</a>
        {% endif %}
    {% endif %}
</div>
{% endmacro %}

application/templates/forum/thread.html
{% extends 'forum/layout.html' %}
{% import 'forum/macros.html' as m %}

{% block title %}{{ thread.name }}{% endblock %}

{% block body %}
{{ m.breadcrumbs(board, thread) }}
<h1>{{ thread.name }}</h1>

<a href="{{ url_for('.create_post', slug=board.slug, id=thread.id) }}">New post</a>

{% for p in posts %}
<article class="post">
    <a href="{{ url_for('.user', id=p.author_id) }}">{{ p.author.email }}</a>
    {{ p.readable_date(p.created) }}
    {{ p.content|markdown }}
    {% if p.author_id == current_user.id %}<a href="{{ url_for('.edit_post', slug=board.slug, thread_id=thread.id, post_id=p.id) }}">[edit]</a>{% endif %}
</article>
{% endfor %}
{% endblock %}

application/templates/forum/user.html
{% extends 'forum/layout.html' %}
{% import 'forum/macros.html' as m %}

{% block title %}{{ user.email }}{% endblock %}

{% block body %}
{{ m.breadcrumbs() }}
<h1>{{ user.email }}</h1>

{% endblock %}